version: '3.8'

services:
  app:
    build: .
    container_name: songvote-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/songvote?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=add_your_own_jwt_secret_here
      - ENCRYPTION_KEY=add_your_own_encryption_key_here
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - db
      - redis
    volumes:
      # PERSIST UPLOADS HERE
      - uploads_data:/app/public/uploads

  db:
    image: postgres:15-alpine
    container_name: songvote-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=songvote
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: songvote-redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  uploads_data: