version: '3.8'

services:
  app:
    build: .
    container_name: songvote-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/songvote?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=JWT_SECRET=f27a5046ea27a0053eff583e4b0af1e1c0b2cf44399447b0e33e4e33d1e2372a
      - ENCRYPTION_KEY=a4925bd7677e24c13b629515a5791efa1ddb22d5d99a720327450f56fd878e2e
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: songvote-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=songvote
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: songvote-redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: